/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.n2.sprintburst.view.banHang;

import entities.receipts.HoaDon;
import entities.receipts.HoaDonChiTiet;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import repositories.receipts.HoaDonRepository;
import responses.HoaDonResponse;
import services.HoaDonService;
import utils.MaGenerator;

/**
 *
 * @author Mtt
 */
public class BanHangForm extends javax.swing.JPanel {

    List<HoaDonResponse> hoaDonStateAll;
    List<HoaDonChiTiet> hoaDonChiTietStateAll;

    HoaDonResponse hoaDonStateCurr;
    List<HoaDonChiTiet> hoaDonChiTietStateCurr;

    HoaDonRepository hdrp;

    DefaultTableModel newHdTblModel;

    /**
     * Creates new form Welcome
     */
    public BanHangForm() {
        initComponents();

        hdrp = new HoaDonRepository();

        newHdTblModel = (DefaultTableModel) tblNewHoaDon.getModel();

        hoaDonStateAll = new HoaDonService().selectNew();

        renderDisplays();

    }

    private void renderNewHoaDonTable() {

        newHdTblModel.setRowCount(0);

        int num = 1;
        for (HoaDonResponse row : hoaDonStateAll) {
            newHdTblModel.addRow(new Object[]{num, row.getMaHoaDon(), row.getTenKhachHang(), row.getDienThoai(), row.getNgayTao(), row.getTenTaiKhoan(), row.getTrangThaiHoaDon() == 1 ? "Chưa thanh toán" : ""});
            num++;
        }

    }

    private void renderCurrHoaDonLabels() {
        if (hoaDonStateCurr != null) {
            txtTenKhachHang.setText(hoaDonStateCurr.getTenKhachHang());
            txtSdt.setText(hoaDonStateCurr.getDienThoai());
            txtMaKhachHang.setText(hoaDonStateCurr.getMaKhachHang());
            txtGiaTri.setText(String.valueOf(hoaDonStateCurr.getGiaTri()));
            txtGiaTriTong.setText(String.valueOf(hoaDonStateCurr.getGiaTriTong()));
        } else {
            txtTenKhachHang.setText("");
            txtSdt.setText("");
            txtMaKhachHang.setText("");
            txtGiaTri.setText("");
            txtGiaTriTong.setText("");
        }
    }

    private void renderDisplays() {
        renderNewHoaDonTable();
        renderCurrHoaDonLabels();

    }

    private void renderHoaDonInfoFromTable() {
        int idx = tblNewHoaDon.getSelectedRow();
        HoaDonResponse found = hoaDonStateAll.get(idx);
        hoaDonStateCurr = found;

        renderCurrHoaDonLabels();

    }

    private void addKhachHangToHoaDOn() {
        try {

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public static void main(String[] args) {
        new BanHangForm().setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrBaoHanh = new javax.swing.ButtonGroup();
        txtTimKiem = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        TapDonHang = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDonHang = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNewHoaDon = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtKhachHang = new javax.swing.JTextField();
        btnKhachHang = new javax.swing.JButton();
        lblTongTien = new javax.swing.JLabel();
        lblVAT = new javax.swing.JLabel();
        lblChietKhau = new javax.swing.JLabel();
        lblKhachPhaiTra = new javax.swing.JLabel();
        lblTienMat = new javax.swing.JLabel();
        lblTienThua = new javax.swing.JLabel();
        lblTenKhachHang = new javax.swing.JLabel();
        lblSDT = new javax.swing.JLabel();
        lblMaKhachHang = new javax.swing.JLabel();
        txtTenKhachHang = new javax.swing.JLabel();
        txtSdt = new javax.swing.JLabel();
        txtMaKhachHang = new javax.swing.JLabel();
        txtGiaTri = new javax.swing.JLabel();
        txtVAT = new javax.swing.JLabel();
        txtGiaTriTong = new javax.swing.JLabel();
        TienThua = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtChietKhau = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtTienMat = new javax.swing.JTextField();
        lblChuyenKhoan = new javax.swing.JLabel();
        txtTienThe = new javax.swing.JTextField();
        lblVND1 = new javax.swing.JLabel();
        lblVND2 = new javax.swing.JLabel();
        lblVND3 = new javax.swing.JLabel();
        lblVND4 = new javax.swing.JLabel();
        lblVND5 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnChietKhau = new javax.swing.JButton();
        btnKhuyenMai = new javax.swing.JButton();
        btnGhiChu = new javax.swing.JButton();
        btnXoaGioHang = new javax.swing.JButton();
        btnDanhSachDon = new javax.swing.JButton();
        btnAddKhachHang = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();
        lblTaoDonHang = new javax.swing.JLabel();
        txtCreateHoaDon = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblTenSP = new javax.swing.JLabel();
        TenSP = new javax.swing.JLabel();
        lblMau = new javax.swing.JLabel();
        lblChuoi = new javax.swing.JLabel();
        lblTayCam = new javax.swing.JLabel();
        lblDauCoBan = new javax.swing.JLabel();
        lblNgon = new javax.swing.JLabel();
        lblRen = new javax.swing.JLabel();
        lblTrongLuong = new javax.swing.JLabel();
        lblDuongKinhDau = new javax.swing.JLabel();
        lblThuongHieu = new javax.swing.JLabel();
        lblXuatXu = new javax.swing.JLabel();
        lblBaoHanh = new javax.swing.JLabel();
        lblGiaBan = new javax.swing.JLabel();
        ThuongHieu = new javax.swing.JLabel();
        XuatXu = new javax.swing.JLabel();
        GiaBan = new javax.swing.JLabel();
        btnCheck = new javax.swing.JButton();
        rdo6thang = new javax.swing.JRadioButton();
        rdo12thang = new javax.swing.JRadioButton();
        rdo24thang = new javax.swing.JRadioButton();
        cboMau = new javax.swing.JComboBox<>();
        cboTayCam = new javax.swing.JComboBox<>();
        cboNgon = new javax.swing.JComboBox<>();
        cboChuoi = new javax.swing.JComboBox<>();
        cboTrongLuong = new javax.swing.JComboBox<>();
        cboDuongKinhDau = new javax.swing.JComboBox<>();
        cboDauCoBan = new javax.swing.JComboBox<>();
        cboRen = new javax.swing.JComboBox<>();
        lblSoLuong = new javax.swing.JLabel();
        SoLuong = new javax.swing.JLabel();
        lblVND6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();

        setBorder(new javax.swing.border.MatteBorder(null));
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1677, 1014));
        setMinimumSize(new java.awt.Dimension(1677, 1014));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1677, 1014));

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTimKiem.setToolTipText("");
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/icons8-search-30.png"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        TapDonHang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblDonHang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblDonHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDonHang);
        if (tblDonHang.getColumnModel().getColumnCount() > 0) {
            tblDonHang.getColumnModel().getColumn(0).setResizable(false);
            tblDonHang.getColumnModel().getColumn(1).setResizable(false);
            tblDonHang.getColumnModel().getColumn(2).setResizable(false);
            tblDonHang.getColumnModel().getColumn(3).setResizable(false);
            tblDonHang.getColumnModel().getColumn(4).setResizable(false);
        }

        TapDonHang.addTab("Hóa đơn hiện tại", jScrollPane1);

        tblNewHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblNewHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã", "Tên khách", "SDT", "Ngày tạo", "Người tạo", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNewHoaDon.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblNewHoaDon.getTableHeader().setReorderingAllowed(false);
        tblNewHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNewHoaDonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblNewHoaDon);

        TapDonHang.addTab("Danh sách hóa đơn", jScrollPane2);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKhachHangActionPerformed(evt);
            }
        });

        btnKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnKhachHang.setText("Tìm khách hàng");
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });

        lblTongTien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTongTien.setText("Tổng tiền");

        lblVAT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblVAT.setText("VAT");

        lblChietKhau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblChietKhau.setText("Chiết khấu");

        lblKhachPhaiTra.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblKhachPhaiTra.setText("Khách phải trả");

        lblTienMat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTienMat.setText("Tiền mặt");

        lblTienThua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTienThua.setText("Tiền thừa");

        lblTenKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTenKhachHang.setText("Tên khách hàng");

        lblSDT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSDT.setText("Số điện thoại");

        lblMaKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaKhachHang.setText("Mã khách hàng");

        txtTenKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTenKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtTenKhachHang.setText("Nguyễn Văn A");

        txtSdt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSdt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtSdt.setText("0912345678");

        txtMaKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMaKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtMaKhachHang.setText("jLabel11");

        txtGiaTri.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtGiaTri.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtGiaTri.setText("3.000.000");

        txtVAT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtVAT.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtVAT.setText("300.000");

        txtGiaTriTong.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtGiaTriTong.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtGiaTriTong.setText("3.000.000");

        TienThua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TienThua.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TienThua.setText("500.000");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        txtChietKhau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtChietKhau.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtChietKhau.setText("300.000");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        txtTienMat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTienMat.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTienMat.setText("3.500.000");
        txtTienMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienMatActionPerformed(evt);
            }
        });

        lblChuyenKhoan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblChuyenKhoan.setText("Chuyển khoản");

        txtTienThe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTienThe.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTienThe.setText("0");
        txtTienThe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienTheActionPerformed(evt);
            }
        });

        lblVND1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblVND1.setText("VND");

        lblVND2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblVND2.setText("VND");

        lblVND3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblVND3.setText("VND");

        lblVND4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblVND4.setText("VND");

        lblVND5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblVND5.setText("VND");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVAT)
                            .addComponent(lblChietKhau)
                            .addComponent(lblTienMat)
                            .addComponent(lblKhachPhaiTra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(txtTienMat, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTienThua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TienThua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)
                        .addComponent(lblVND5)
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblChuyenKhoan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTienThe, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTongTien)
                                .addGap(81, 81, 81)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(txtChietKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblVND3)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtVAT, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblVND2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtGiaTri, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblVND1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtGiaTriTong, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblVND4))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTenKhachHang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSDT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblMaKhachHang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txtKhachHang))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenKhachHang)
                    .addComponent(txtTenKhachHang))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSDT)
                    .addComponent(txtSdt))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaKhachHang)
                    .addComponent(txtMaKhachHang))
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lblTongTien))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGiaTri)
                            .addComponent(lblVND1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVND2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblVAT)
                        .addComponent(txtVAT)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblChietKhau)
                            .addComponent(lblVND3))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtChietKhau)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKhachPhaiTra)
                    .addComponent(txtGiaTriTong, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVND4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTienMat)
                    .addComponent(txtTienMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChuyenKhoan)
                    .addComponent(txtTienThe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblTienThua))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVND5))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/icons8-plus-math-30.png"))); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnChietKhau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnChietKhau.setText("Chiết khấu");
        btnChietKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChietKhauActionPerformed(evt);
            }
        });

        btnKhuyenMai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnKhuyenMai.setText("Khuyến mại");
        btnKhuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhuyenMaiActionPerformed(evt);
            }
        });

        btnGhiChu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGhiChu.setText("Ghi chú");
        btnGhiChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiChuActionPerformed(evt);
            }
        });

        btnXoaGioHang.setBackground(new java.awt.Color(255, 0, 0));
        btnXoaGioHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoaGioHang.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaGioHang.setText("Xóa giỏ hàng");
        btnXoaGioHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaGioHangActionPerformed(evt);
            }
        });

        btnDanhSachDon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDanhSachDon.setText("Danh sách đơn");
        btnDanhSachDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhSachDonActionPerformed(evt);
            }
        });

        btnAddKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAddKhachHang.setText("Thêm khách hàng");
        btnAddKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddKhachHangActionPerformed(evt);
            }
        });

        btnThanhToan.setBackground(new java.awt.Color(0, 204, 0));
        btnThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        btnThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhToan.setText("Thanh toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        lblTaoDonHang.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTaoDonHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTaoDonHang.setText("Tạo đơn hàng");

        txtCreateHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCreateHoaDon.setText("Tạo hóa đơn mới");
        txtCreateHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreateHoaDonActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTenSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenSP.setText("Tên sản phẩm:");

        TenSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TenSP.setText("Gậy ABCDEF");

        lblMau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMau.setText("Màu sắc");

        lblChuoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblChuoi.setText("Chuôi");

        lblTayCam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTayCam.setText("Tay cầm");

        lblDauCoBan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDauCoBan.setText("Đầu cơ bản");

        lblNgon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNgon.setText("Ngọn");

        lblRen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRen.setText("Ren");

        lblTrongLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTrongLuong.setText("Trọng lượng");

        lblDuongKinhDau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDuongKinhDau.setText("Đường kính đầu");

        lblThuongHieu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblThuongHieu.setText("Thương hiệu:");

        lblXuatXu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblXuatXu.setText("Xuất xứ:");

        lblBaoHanh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBaoHanh.setText("Bảo hành");

        lblGiaBan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGiaBan.setText("Giá bán");

        ThuongHieu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ThuongHieu.setText("ABC\\");

            XuatXu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            XuatXu.setText("ABC\\");

                GiaBan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                GiaBan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                GiaBan.setText("500.000");

                btnCheck.setText("Check");
                btnCheck.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnCheckActionPerformed(evt);
                    }
                });

                GrBaoHanh.add(rdo6thang);
                rdo6thang.setText("6 Tháng");
                rdo6thang.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        rdo6thangActionPerformed(evt);
                    }
                });

                GrBaoHanh.add(rdo12thang);
                rdo12thang.setText("12 Tháng");
                rdo12thang.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        rdo12thangActionPerformed(evt);
                    }
                });

                GrBaoHanh.add(rdo24thang);
                rdo24thang.setText("24 Tháng");
                rdo24thang.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        rdo24thangActionPerformed(evt);
                    }
                });

                cboMau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                cboTayCam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                cboNgon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                cboChuoi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                cboTrongLuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                cboDuongKinhDau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                cboDauCoBan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                cboRen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                lblSoLuong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                lblSoLuong.setText("Số lượng");

                SoLuong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                SoLuong.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                SoLuong.setText("10");

                lblVND6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                lblVND6.setText("VND");

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                    jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lblTenSP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblThuongHieu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(lblMau)
                                        .addGap(18, 18, 18)
                                        .addComponent(cboMau, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTayCam)
                                            .addComponent(lblNgon)
                                            .addComponent(lblChuoi))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cboChuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cboNgon, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cboTayCam, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTrongLuong)
                                    .addComponent(lblDuongKinhDau)
                                    .addComponent(lblDauCoBan)
                                    .addComponent(lblRen))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboRen, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboDauCoBan, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboDuongKinhDau, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboTrongLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lblBaoHanh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdo6thang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdo12thang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdo24thang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCheck)))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lblXuatXu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(XuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lblSoLuong)
                                .addGap(18, 18, 18)
                                .addComponent(SoLuong))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lblGiaBan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblVND6)))
                        .addGap(42, 42, 42))
                );
                jPanel5Layout.setVerticalGroup(
                    jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTenSP)
                            .addComponent(TenSP)
                            .addComponent(lblThuongHieu)
                            .addComponent(ThuongHieu)
                            .addComponent(lblXuatXu)
                            .addComponent(XuatXu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMau)
                            .addComponent(lblTrongLuong)
                            .addComponent(cboMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboTrongLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDuongKinhDau)
                            .addComponent(lblTayCam)
                            .addComponent(cboTayCam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboDuongKinhDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDauCoBan)
                            .addComponent(lblNgon)
                            .addComponent(cboNgon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboDauCoBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRen)
                            .addComponent(lblChuoi)
                            .addComponent(cboChuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboRen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSoLuong)
                            .addComponent(SoLuong))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBaoHanh)
                            .addComponent(rdo6thang)
                            .addComponent(rdo12thang)
                            .addComponent(rdo24thang)
                            .addComponent(btnCheck)
                            .addComponent(lblGiaBan)
                            .addComponent(GiaBan)
                            .addComponent(lblVND6)))
                );

                jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

                tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null}
                    },
                    new String [] {
                        "Mã sản phẩm", "Tên sản phẩm", "Thương hiệu", "Xuất xứ", "Số lượng"
                    }
                ));
                jScrollPane3.setViewportView(tblSanPham);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btnChietKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(btnKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(btnAddKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(btnDanhSachDon)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(btnGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addComponent(txtCreateHoaDon, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addGap(10, 10, 10)
                                            .addComponent(btnXoaGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(TapDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(201, 201, 201))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTaoDonHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(113, 113, 113))))
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblTaoDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCreateHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TapDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXoaGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnChietKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAddKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnDanhSachDon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(238, Short.MAX_VALUE))
                );

                getAccessibleContext().setAccessibleName("");
            }// </editor-fold>//GEN-END:initComponents

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void txtKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKhachHangActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnChietKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChietKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChietKhauActionPerformed

    private void btnKhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhuyenMaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKhuyenMaiActionPerformed

    private void btnGhiChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiChuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGhiChuActionPerformed

    private void btnXoaGioHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaGioHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaGioHangActionPerformed

    private void btnDanhSachDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhSachDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDanhSachDonActionPerformed

    private void btnAddKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddKhachHangActionPerformed
        addKhachHangToHoaDOn();    }//GEN-LAST:event_btnAddKhachHangActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void txtTienMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienMatActionPerformed

    private void txtTienTheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienTheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienTheActionPerformed

    private void txtCreateHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreateHoaDonActionPerformed
        try {
            HoaDon newHoaDon = HoaDon.builder()
                    .idKhachHang(null)
                    .idGiamGiaHoaDon(null)
                    .idTaiKhoan(null)
                    .maHoaDon(MaGenerator.generateByNum("HD", hdrp.getLastId()))
                    .build();

            if (JOptionPane.OK_OPTION == JOptionPane.showConfirmDialog(this, "Tạo?"));
            hdrp.create(newHoaDon);

            hoaDonStateAll = new HoaDonService().selectNew();
            hoaDonStateCurr = null;

            renderDisplays();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_txtCreateHoaDonActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckActionPerformed

    private void rdo6thangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo6thangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo6thangActionPerformed

    private void rdo12thangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo12thangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo12thangActionPerformed

    private void rdo24thangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo24thangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdo24thangActionPerformed

    private void tblNewHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNewHoaDonMouseClicked
        renderHoaDonInfoFromTable();
    }//GEN-LAST:event_tblNewHoaDonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GiaBan;
    private javax.swing.ButtonGroup GrBaoHanh;
    private javax.swing.JLabel SoLuong;
    private javax.swing.JTabbedPane TapDonHang;
    private javax.swing.JLabel TenSP;
    private javax.swing.JLabel ThuongHieu;
    private javax.swing.JLabel TienThua;
    private javax.swing.JLabel XuatXu;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddKhachHang;
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnChietKhau;
    private javax.swing.JButton btnDanhSachDon;
    private javax.swing.JButton btnGhiChu;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnKhuyenMai;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnXoaGioHang;
    private javax.swing.JComboBox<String> cboChuoi;
    private javax.swing.JComboBox<String> cboDauCoBan;
    private javax.swing.JComboBox<String> cboDuongKinhDau;
    private javax.swing.JComboBox<String> cboMau;
    private javax.swing.JComboBox<String> cboNgon;
    private javax.swing.JComboBox<String> cboRen;
    private javax.swing.JComboBox<String> cboTayCam;
    private javax.swing.JComboBox<String> cboTrongLuong;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblBaoHanh;
    private javax.swing.JLabel lblChietKhau;
    private javax.swing.JLabel lblChuoi;
    private javax.swing.JLabel lblChuyenKhoan;
    private javax.swing.JLabel lblDauCoBan;
    private javax.swing.JLabel lblDuongKinhDau;
    private javax.swing.JLabel lblGiaBan;
    private javax.swing.JLabel lblKhachPhaiTra;
    private javax.swing.JLabel lblMaKhachHang;
    private javax.swing.JLabel lblMau;
    private javax.swing.JLabel lblNgon;
    private javax.swing.JLabel lblRen;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTaoDonHang;
    private javax.swing.JLabel lblTayCam;
    private javax.swing.JLabel lblTenKhachHang;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JLabel lblThuongHieu;
    private javax.swing.JLabel lblTienMat;
    private javax.swing.JLabel lblTienThua;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JLabel lblTrongLuong;
    private javax.swing.JLabel lblVAT;
    private javax.swing.JLabel lblVND1;
    private javax.swing.JLabel lblVND2;
    private javax.swing.JLabel lblVND3;
    private javax.swing.JLabel lblVND4;
    private javax.swing.JLabel lblVND5;
    private javax.swing.JLabel lblVND6;
    private javax.swing.JLabel lblXuatXu;
    private javax.swing.JRadioButton rdo12thang;
    private javax.swing.JRadioButton rdo24thang;
    private javax.swing.JRadioButton rdo6thang;
    private javax.swing.JTable tblDonHang;
    private javax.swing.JTable tblNewHoaDon;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JLabel txtChietKhau;
    private javax.swing.JButton txtCreateHoaDon;
    private javax.swing.JLabel txtGiaTri;
    private javax.swing.JLabel txtGiaTriTong;
    private javax.swing.JTextField txtKhachHang;
    private javax.swing.JLabel txtMaKhachHang;
    private javax.swing.JLabel txtSdt;
    private javax.swing.JLabel txtTenKhachHang;
    private javax.swing.JTextField txtTienMat;
    private javax.swing.JTextField txtTienThe;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JLabel txtVAT;
    // End of variables declaration//GEN-END:variables
}
