/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.n2.sprintburst.view;

import com.n2.sprintburst.entity.HoaDon;
import com.n2.sprintburst.service.HoaDonService;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class LichSuGiaoDichView extends javax.swing.JFrame {

    DefaultTableModel defaultTableModel1 = new DefaultTableModel();
    HoaDonService hoaDonService = new HoaDonService();
    List<HoaDon> hd = new ArrayList<>();
    
    int idKhachHang ;
    /**
     * Creates new form LichSuGiaoDichView
     */
    public LichSuGiaoDichView() {
        System.out.println("kh view id"+ KhachHangView.idChon);
        idKhachHang=KhachHangView.idChon;
        initComponents();
        setLocationRelativeTo(null);
        setUpTableLichSuGiaoDaoDich();
        fillDataLichSu();
        defaultTableModel1 = (DefaultTableModel) tblBangLichSu.getModel();
    }

    public void setUpTableLichSuGiaoDaoDich() {
        tblBangLichSu.setModel(defaultTableModel1);
        defaultTableModel1.setColumnIdentifiers(new String[]{"Id khách hàng", "Tổng sau giảm giá", "Tổng trước giảm giá", "Ngày tạo", "Tên người nhận"});
    }

    public void fillDataLichSu() {
        hd = hoaDonService.getHoaDonByKhachHangID(idKhachHang);

        defaultTableModel1.setRowCount(0);
        for (HoaDon hoaDon : hd) {
            defaultTableModel1.addRow(new Object[]{
                hoaDon.getKhachHang().getId(),
                hoaDon.getTongSauGiamGia(),
                hoaDon.getTongTruocGiamGia(),
                hoaDon.getNgayTao(),
                hoaDon.getTenNguoiNhan(),});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBangLichSu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblBangLichSu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBangLichSu);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Lịch sử giao dịch");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBangLichSu;
    // End of variables declaration//GEN-END:variables
}
