/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.n2.sprintburst.view.sanPham;

import com.formdev.flatlaf.FlatLightLaf;
import com.n2.sprintburst.service.ThuocTinhService;
import com.n2.sprintburst.view.sanPham.SanPhamChiTietCreateview;
import javax.swing.JComponent;

/**
 *
 * @author Mtt
 */
public class CreateThuocTinhForm extends javax.swing.JFrame {

    String tbl;
    SanPhamChiTietOperationForm parent;

    /**
     * Creates new form CreateThuocTinhForm
     */
    public CreateThuocTinhForm(String tbl, SanPhamChiTietOperationForm parent) {
        FlatLightLaf.setup();

        initComponents();

        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        this.tbl = tbl;
        this.parent = parent;
    }

    private void addThuocTinh() {
        ThuocTinhService.add(txtThuocTinhCreate.getText(), tbl);
        this.dispose();

        parent.initCbxData();
        parent.initCbxUI();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtThuocTinhCreate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnThuocTinhCreate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(312, 160));

        jLabel1.setText("Tên");

        txtThuocTinhCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThuocTinhCreateActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("THÊM THUỘC TÍNH");

        btnThuocTinhCreate.setText("Thêm");
        btnThuocTinhCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuocTinhCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtThuocTinhCreate))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(btnThuocTinhCreate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtThuocTinhCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnThuocTinhCreate)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtThuocTinhCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThuocTinhCreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThuocTinhCreateActionPerformed

    private void btnThuocTinhCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuocTinhCreateActionPerformed
        addThuocTinh();
    }//GEN-LAST:event_btnThuocTinhCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThuocTinhCreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtThuocTinhCreate;
    // End of variables declaration//GEN-END:variables
}
