/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.n2.sprintburst.view.sanPham;

import com.n2.sprintburst.entity.SanPham;
import com.n2.sprintburst.service.SanPhamService;
import com.n2.sprintburst.utils.PlaceHolderdata;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mtt
 */
public class SanPhamView extends javax.swing.JPanel {

    //COMPONENT MODELS
    private DefaultTableModel sanPhamTableModel;

    /**
     * Creates new form SanPhamView
     */
    public SanPhamView() {
        PlaceHolderdata.insertData();

        initComponents();

        //init component models
        sanPhamTableModel = (DefaultTableModel) tblSanPham.getModel();
    }

    private void initSanPhamTable() {
        sanPhamTableModel.setRowCount(0);
        List<SanPham> list = SanPhamService.getAllActive();

        for (int i = 0; i < list.size(); i++) {
            SanPham sp = list.get(i);
            sanPhamTableModel.addRow(new Object[]{
                i + 1,
                sp.getMaSanPham(),
                sp.getTenSanPham(),
                sp.
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        sanPhamTab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addPanel = new javax.swing.JPanel();
        txtAddSanPhamName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAddSanPham = new javax.swing.JButton();
        actionPanel = new javax.swing.JPanel();
        btnEditSanPham = new javax.swing.JButton();
        btnDeleteSanPham = new javax.swing.JButton();
        btnAddSanPhamChiTiet = new javax.swing.JButton();
        btnResetFormSanPhamTab = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        sanPhamChiTietTab = new javax.swing.JPanel();
        thuocTinhTab = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(900, 600));

        sanPhamTab.setMaximumSize(new java.awt.Dimension(900, 600));
        sanPhamTab.setMinimumSize(new java.awt.Dimension(900, 600));
        sanPhamTab.setPreferredSize(new java.awt.Dimension(900, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN SẢN PHẨM");

        addPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addPanel.setPreferredSize(new java.awt.Dimension(420, 100));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Thêm sản phẩm mới");

        jLabel3.setText("Tên");

        btnAddSanPham.setText("Thêm");

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtAddSanPhamName, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddSanPham))
                    .addComponent(jLabel2))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddSanPhamName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnAddSanPham))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        actionPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        actionPanel.setPreferredSize(new java.awt.Dimension(420, 100));

        btnEditSanPham.setText("Sửa");
        btnEditSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditSanPhamActionPerformed(evt);
            }
        });

        btnDeleteSanPham.setText("Xóa");
        btnDeleteSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSanPhamActionPerformed(evt);
            }
        });

        btnAddSanPhamChiTiet.setText("Thêm SPCT");
        btnAddSanPhamChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSanPhamChiTietActionPerformed(evt);
            }
        });

        btnResetFormSanPhamTab.setText("Reset form");
        btnResetFormSanPhamTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetFormSanPhamTabActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionPanelLayout = new javax.swing.GroupLayout(actionPanel);
        actionPanel.setLayout(actionPanelLayout);
        actionPanelLayout.setHorizontalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actionPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEditSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetFormSanPhamTab, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddSanPhamChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        actionPanelLayout.setVerticalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditSanPham)
                    .addComponent(btnDeleteSanPham))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddSanPhamChiTiet)
                    .addComponent(btnResetFormSanPhamTab))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã", "Tên", "Số lượng", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSanPham);

        javax.swing.GroupLayout sanPhamTabLayout = new javax.swing.GroupLayout(sanPhamTab);
        sanPhamTab.setLayout(sanPhamTabLayout);
        sanPhamTabLayout.setHorizontalGroup(
            sanPhamTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sanPhamTabLayout.createSequentialGroup()
                .addGroup(sanPhamTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sanPhamTabLayout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sanPhamTabLayout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addGroup(sanPhamTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(sanPhamTabLayout.createSequentialGroup()
                                .addComponent(addPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(actionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18))
        );
        sanPhamTabLayout.setVerticalGroup(
            sanPhamTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sanPhamTabLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(sanPhamTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("SẢN PHẨM", sanPhamTab);

        javax.swing.GroupLayout sanPhamChiTietTabLayout = new javax.swing.GroupLayout(sanPhamChiTietTab);
        sanPhamChiTietTab.setLayout(sanPhamChiTietTabLayout);
        sanPhamChiTietTabLayout.setHorizontalGroup(
            sanPhamChiTietTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 905, Short.MAX_VALUE)
        );
        sanPhamChiTietTabLayout.setVerticalGroup(
            sanPhamChiTietTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("CHI TIẾT SẢN PHẨM", sanPhamChiTietTab);

        javax.swing.GroupLayout thuocTinhTabLayout = new javax.swing.GroupLayout(thuocTinhTab);
        thuocTinhTab.setLayout(thuocTinhTabLayout);
        thuocTinhTabLayout.setHorizontalGroup(
            thuocTinhTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 905, Short.MAX_VALUE)
        );
        thuocTinhTabLayout.setVerticalGroup(
            thuocTinhTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("THUỘC TÍNH SẢN PHẨM", thuocTinhTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditSanPhamActionPerformed

    private void btnDeleteSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteSanPhamActionPerformed

    private void btnAddSanPhamChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSanPhamChiTietActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddSanPhamChiTietActionPerformed

    private void btnResetFormSanPhamTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetFormSanPhamTabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetFormSanPhamTabActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JPanel addPanel;
    private javax.swing.JButton btnAddSanPham;
    private javax.swing.JButton btnAddSanPhamChiTiet;
    private javax.swing.JButton btnDeleteSanPham;
    private javax.swing.JButton btnEditSanPham;
    private javax.swing.JButton btnResetFormSanPhamTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel sanPhamChiTietTab;
    private javax.swing.JPanel sanPhamTab;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JPanel thuocTinhTab;
    private javax.swing.JTextField txtAddSanPhamName;
    // End of variables declaration//GEN-END:variables
}
